name: student_list_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  excel: ^2.1.0      # <-- เพิ่มบรรทัดนี้ สำหรับใช้งาน Excel

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mylogo.png
    - assets/students.xlsx   # <-- เพิ่มบรรทัดนี้ สำหรับไฟล์ Excel (ต้องวางไฟล์ในโฟลเดอร์นี้)
